# Generated by Django 3.1.2 on 2020-10-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionstats',
            name='correct',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
