# Generated by Django 3.1.2 on 2020-10-27 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollresults',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.questionnaire'),
        ),
        migrations.AlterField(
            model_name='pollresults',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
