# Generated by Django 3.1.2 on 2020-10-26 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_questionstats_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('results', models.JSONField()),
                ('questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.questionnaire')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
